// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8QsNzj6iVbL7OEoWO771SinZeaT9u_Ic',
    appId: '1:500302745857:web:c502d92e40fabf9702cb00',
    messagingSenderId: '500302745857',
    projectId: 'movie-explorer-d4c7a',
    authDomain: 'movie-explorer-d4c7a.firebaseapp.com',
    storageBucket: 'movie-explorer-d4c7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiRiVwQzrUPtPx36xi7rIYAbiB-8j90iE',
    appId: '1:500302745857:android:d2d20c662df5a05e02cb00',
    messagingSenderId: '500302745857',
    projectId: 'movie-explorer-d4c7a',
    storageBucket: 'movie-explorer-d4c7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_v6ADi7VKFIhn34P6eyBei3A0MU-TI_s',
    appId: '1:500302745857:ios:f03bfee3fafad03c02cb00',
    messagingSenderId: '500302745857',
    projectId: 'movie-explorer-d4c7a',
    storageBucket: 'movie-explorer-d4c7a.firebasestorage.app',
    iosBundleId: 'com.example.movieExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_v6ADi7VKFIhn34P6eyBei3A0MU-TI_s',
    appId: '1:500302745857:ios:f03bfee3fafad03c02cb00',
    messagingSenderId: '500302745857',
    projectId: 'movie-explorer-d4c7a',
    storageBucket: 'movie-explorer-d4c7a.firebasestorage.app',
    iosBundleId: 'com.example.movieExplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8QsNzj6iVbL7OEoWO771SinZeaT9u_Ic',
    appId: '1:500302745857:web:eed694820b74297f02cb00',
    messagingSenderId: '500302745857',
    projectId: 'movie-explorer-d4c7a',
    authDomain: 'movie-explorer-d4c7a.firebaseapp.com',
    storageBucket: 'movie-explorer-d4c7a.firebasestorage.app',
  );
}
